# This workflow regularly checks for new tags in Betterbird/thunderbird-patches, 
# runs ./update-version.sh $tag if there is a new tag, and commits the result
# on a new branch named update-$tag that branches off from develop.

name: update-version

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */6 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: eu.betterbird.Betterbird
          ref: develop
      - uses: actions/checkout@v3
        with:
          repository: Betterbird/thunderbird-patches
          path: thunderbird-patches
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Checking for new tags
        run: |
          auto_update_major_release=102
          cd thunderbird-patches
          all_tags=$(git tag | sort)
          new_tags=$(comm -23 <(echo "${all_tags}") <(sort ../eu.betterbird.Betterbird/.known-tags))
          cd ../eu.betterbird.Betterbird
          if [[ -n $new_tags ]]
          then
            echo " --- New tags: $new_tags ---"
            for tag in ${new_tags}
            do
              if [[ $(echo $tag | cut -f1 -d.) == $auto_update_major_release ]]
              then
                target_tag=$tag
              fi
            done
            if [[ -n $target_tag ]]
            then
              echo " --- Updating to $target_tag ---"
              git config user.name github-actions
              git config user.email github-actions@github.com
              ./update-version.sh $target_tag \
              && echo "${all_tags}" > .known-tags \
              && git switch -c "update-$target_tag" \
              && git commit -m "Update to $target_tag" -- .known-tags eu.betterbird.Betterbird.json thunderbird-sources.json \
              && git push --set-upstream origin "update-$target_tag" \
              || exit 1
            fi
          else
            echo " --- No new tags found ---"
          fi
          
