# This workflow checks for new tags in Betterbird/thunderbird-patches and runs
# update-version.py --auto if there is a new tag for the configured major
# release. It prepares the update on the develop branch and creates a PR that
# merges develop into master.

name: update-version

on:
  #schedule:
  #  - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install GitPython PyYAML

      - name: Auto-update to newest tag
        run: python update-version.py --auto 153 --base develop --target master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
