# This workflow regularly checks for new tags in Betterbird/thunderbird-patches, 
# runs ./update-version.sh $tag if there is a new tag, commits the result to the
# develop branch and creates a PR for merging develop into master.

name: update-version

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: eu.betterbird.Betterbird
          ref: develop
      - uses: actions/checkout@v3
        with:
          repository: Betterbird/thunderbird-patches
          path: thunderbird-patches
          fetch-depth: 0

      # Checks for new upstream tags and updates the manifest if new
      # tags are available
      - name: Auto-update to newest tag
        run: ./eu.betterbird.Betterbird/.github/scripts/auto-update.sh
      
      # Creates a PR to merge develop into master if Betterbird has
      # been updated
      - name: Create Pull Request
        if: ${{env.version_updated=='true'}}
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          path: eu.betterbird.Betterbird
          branch: develop
          delete-branch: false
          base: master
          title: Update Betterbird to ${{env.new_version}}
      
