# This is a basic workflow to help you get started with Actions

name: update-version

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */1 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: eu.betterbird.Betterbird
      - uses: actions/checkout@v3
        with:
          repository: Betterbird/thunderbird-patches
          path: thunderbird-patches
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Checking for new tags
        id: check-new-tags
        run: |
          echo "::set-output name=update_needed::false"
          auto_update_major_release=102
          cd thunderbird-patches
          new_tags=$(comm -23 <(git tag | sort) <(sort ../eu.betterbird.Betterbird/.known-tags))
          cd ../eu.betterbird.Betterbird
          if [[ -n $new_tags ]]
          then
            echo " --- New tags: $new_tags ---"
            for tag in ${new_tags}
            do
              if [[ $(echo $tag | cut -f1 -d.) == $auto_update_major_release ]]
              then
                target_tag=$tag
              fi
            done
            if [[ -n $target_tag ]]
            then
              echo " --- Target version: $target_tag ---"
              echo "::set-output name=update_needed::true"
              echo "::set-output name=target_tag::$target_tag"
            fi
          else
            echo " --- No new tags found ---"
          fi
      - if: ${{ steps.check-new-tags.outputs.update_needed == 'true' }}
        name: Updating manifest
        id: update-manifest
        run: |
          target_tag=${{ steps.check-new-tags.outputs.target_tag }}
          echo " --- Updating to $target_tag ---"
          ./update-version.sh $target_tag \
          && echo $target_tag >> .known-tags \
          || exit 1
          
      - if: ${{ steps.check-new-tags.outputs.update_needed == 'true' }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          path: eu.betterbird.Betterbird
          add-paths: .known-tags,eu.betterbird.Betterbird.json,thunderbird-sources.json
          commit-message: Update to ${{ steps.check-new-tags.outputs.target_tag }}
          branch: update-${{ steps.check-new-tags.outputs.target_tag }}
          delete-branch: true
          title: Update to ${{ steps.check-new-tags.outputs.target_tag }}
          body: Update to ${{ steps.check-new-tags.outputs.target_tag }}
